#! /bin/sh

# config options
bspc config border_width        1
bspc config window_gap          16
bspc config split_ratio         0.6180339887
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

# colors
bspc config focused_border_color "#dc322f"
bspc config normal_border_color "#111111"
bspc config presel_border_color "#859900"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc desktop ^1 -l monocle

# rules
# bspc config external_rules_command "$XDG_CONFIG_HOME/bspwm/external_rules"
bspc rule -a feh floating=on
bspc rule -a sxiv floating=on
bspc rule -a mpv floating=on
# bspc rule -a RANGER floating=on
bspc rule -a pcmanfm floating=on

# autostart apps
[ -x /usr/bin/xautolock ] && /usr/bin/xautolock &
sxhkd &
panel &
