#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width        1
bspc config window_gap          -1
bspc config split_ratio         0.6180339887
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# bspc config focused_border_color "#dc322f"

bspc rule -a feh floating=on
bspc rule -a mpv floating=on
bspc rule -a RANGER floating=on

# Restore
# if [ -e "$BSPWM_TREE" ] ; then
# 	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
# 	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
# fi

sxhkd &
# LANG= ; conky &
panel &
